### ISSUE TITLE
Pls, Help. Your code is not working on my system.

### ISSUE THREAD

**Issue by pcm0124** [WangXuan95/SDcard-File-Reader#2]
I am testing your code (Nexys4-ReadFile) on digiletn arty-a7(artix-7). Using sdhc 16gb fat32.
'sdcardstate' stays forever at 1 (CMD0).
When I check the spi line in the chipscope, cs, mosi, and sck are repeatedly output, but miso stays high.
What should I check?

**Comment by pcm0124** [comment]
I used your sd interface version instead of spi. And the example worked fine. Your code is very good and a good reference.

**Comment by piyonchu** [comment]
Hi, I'm encountering the exact same issue. Unfortunately, my setup only supports SPI mode. I'm wondering if you ever managed to resolve this issue in SPI mode, or found out what the root cause was?
